import React from 'react';
import {Header,Footer,Icon} from './site';

export default function Home(){return <div className="store-page"><Header/><div className="cart-dock"><button type="button" data-cart-open>Lista de carga <span data-pagosya-cart-count data-cart-count>0</span><Icon name="shopping-bag"/></button></div><main>
<section id="cover-001" className="cover"><div className="cover-copy"><p className="eyebrow">ÓRBITA / EXPEDICIÓN 001</p><h1 aria-label="Equipo para otros mundos"><span>EQUIPO</span><span>PARA</span><span>OTROS</span><span>MUNDOS</span></h1><p className="cover-statement">Diseñamos equipo para quienes siempre miran un poco más allá.</p><div className="cover-actions"><a className="button button-accent" href="#field-catalog">Preparar mi expedición <Icon name="arrow-right"/></a><a className="text-link" href="#north-manifesto">Explorar la misión</a></div></div><figure className="cover-photo"><img src="/assets/image-d7a9c0dba65d.jpg" alt="Excursionista contemplando un amplio paisaje rojizo"/><figcaption>CAMPAÑA / TERRENO DESCONOCIDO</figcaption></figure></section>
<section id="expedition-strip" className="expedition-strip"><strong>Expedición 001</strong><span>Terreno desconocido</span><span>04 piezas / 312 configuraciones</span><span className="strip-end">MANUAL DE CAMPO 001</span></section>
<section id="field-catalog" className="catalog-section"><div className="section-heading"><p className="eyebrow">SELECCIÓN DE CAMPO / 01—04</p><h2>ELIGE TU EQUIPO</h2><p>Una colección de prendas y objetos cotidianos inspirada en los paisajes de otro planeta.</p></div><div data-pagosya-catalog></div></section>
<section id="north-manifesto" className="manifesto"><div className="manifesto-copy"><p className="eyebrow">DECLARACIÓN DE MISIÓN / ORB-001</p><h2>LA CURIOSIDAD ES NUESTRO NORTE.</h2><p>Una colección de prendas y objetos cotidianos inspirada en los paisajes de otro planeta. Para salir, explorar y volver con una historia.</p><a className="button button-ink" href="#field-catalog">Ver la colección <Icon name="arrow-right"/></a></div><div className="trajectory" aria-hidden="true"><span className="trajectory-ring ring-one"/><span className="trajectory-ring ring-two"/><span className="trajectory-core">001</span><i/></div></section>
<section id="buying-faq" className="faq"><div><p className="eyebrow">PROTOCOLO DE COMPRA</p><h2>ANTES DE PARTIR</h2></div><div className="faq-list"><details><summary>¿Cómo configuro una pieza?<Icon name="chevron-down"/></summary><p>Abre el detalle del producto y elige una opción en cada grupo. La combinación seleccionada se conserva al añadirla a tu lista de carga.</p></details><details><summary>¿El precio cambia según la configuración?<Icon name="chevron-down"/></summary><p>Sí. El precio mostrado se actualiza con la combinación real que selecciones.</p></details><details><summary>¿Cómo funcionan los Complementos?<Icon name="chevron-down"/></summary><p>Puedes elegir sin complementos, una adición individual o el kit completo. El precio mostrado incluye tu selección.</p></details><details><summary>¿Es equipo espacial certificado?<Icon name="chevron-down"/></summary><p>No. ÓRBITA es una colección conceptual de moda outdoor y objetos cotidianos, presentada como tienda de demostración.</p></details></div></section>
</main><div data-pagosya-cart hidden></div><div data-pagosya-contact hidden></div><div data-pagosya-status role="status" aria-live="polite"></div><Footer/></div>}
