import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const commerce = readFileSync(new URL('../../api/src/stores/source-kit/commerce.js', import.meta.url), 'utf8');
const store = { storeName: 'Taller Alba', checkoutMode: 'payment', categories: [], items: [{ id: 'p1', name: 'Bolso de algodón', amount: 15000, currency: 'BOB', stock: 5, imageUrls: [] }], locations: [{ id: 'central', name: 'Taller central', address: 'Calle 10, La Paz', pickupEnabled: true, deliveryEnabled: true }, { id: 'closed', name: 'Sucursal sin entregas', pickupEnabled: false, deliveryEnabled: false }] };

for (const width of [1280, 390]) test(`cart drawer and full-page fulfillment at ${width}px`, async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width, height: 900 });
  await page.route('https://shop.test/**', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;margin:0;padding:32px;--paper:#fffdf8;--ink:#25271e;--accent:#0750a4}nav{display:flex;justify-content:space-between;align-items:center}button{font:inherit;min-height:44px}.menu-item{max-width:600px;padding:40px 0}.menu-add{min-width:44px}</style><nav><h1>Taller Alba</h1><button data-cart-open>Pedido (<span data-cart-count>0</span>)</button></nav><main data-pagosya-catalog></main><div data-pagosya-cart></div><p data-pagosya-status role="status"></p><script>window.PAGOSYA_CONFIG=${JSON.stringify({ demo: true, slug: 'alba', data: store })};</script><script>${commerce}</script></html>` }));
  await page.goto('https://shop.test');
  const trigger = page.getByRole('button', { name: /Pedido \(\s*0\s*\)/ });
  await expect(page.locator('[data-pagosya-cart]')).toBeHidden();
  await trigger.click();
  const drawer = page.getByRole('dialog', { name: 'Tu pedido' });
  await expect(drawer).toContainText('Tu pedido está vacío');
  await expect(drawer.getByRole('button', { name: 'Continuar con mi pedido' })).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await expect(page.locator('[data-pagosya-cart]')).toBeHidden();
  const add = page.getByRole('button', { name: 'Añadir Bolso de algodón', exact: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await add.click(); await add.click();
  expect(await add.evaluate(el => el.getAnimations().length)).toBe(0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await expect(page.locator('.cart-added')).toBeVisible();
  await expect(page.locator('.cart-added')).toContainText('Bolso de algodón añadido');
  await expect(drawer).not.toBeVisible();
  await page.getByRole('button', { name: /Pedido \(\s*2\s*\)/ }).click();
  await expect(drawer.locator('.quantity output')).toHaveText('2');
  await expect(drawer.getByRole('combobox')).toHaveCount(0);
  await expect(drawer).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)');
  const bounds = await drawer.boundingBox();
  expect(bounds!.x + bounds!.width).toBeCloseTo(width, 0);
  expect(bounds!.width).toBeLessThanOrEqual(width > 700 ? width / 2 : width);
  await page.screenshot({ path: `/tmp/pagosya-cart-drawer-${width}.png` });
  await drawer.getByRole('button', { name: 'Quitar una unidad de Bolso de algodón' }).click();
  await expect(drawer.locator('.quantity output')).toHaveText('1');
  await drawer.getByRole('button', { name: 'Continuar con mi pedido' }).click();
  await expect(drawer).not.toBeVisible();
  await expect(page.getByRole('heading', { name: '¿Cómo quieres recibir tu pedido?' })).toBeVisible();
  await expect(page.locator('[data-branch-address]')).toContainText('Calle 10');
  const branch = page.getByRole('combobox', { name: 'Sucursal', exact: true });
  await branch.selectOption('closed');
  expect(await page.locator('[data-checkout-review]').evaluate(panel => { const detail = { panel, valid: true }; document.dispatchEvent(new CustomEvent('pagosya:validate-checkout', { detail })); return detail.valid; })).toBe(false);
  await branch.selectOption('central');
  const method = page.getByRole('combobox', { name: 'Entrega', exact: true });
  await method.selectOption('delivery');
  const address = page.getByRole('textbox', { name: 'Dirección y referencia' });
  await page.getByRole('button', { name: 'Continuar al pago de prueba' }).click();
  await expect(address).toBeFocused();
  await address.fill('Calle 20, puerta verde');
  await page.getByRole('button', { name: 'Añadir una unidad de Bolso de algodón' }).click();
  await expect(address).toHaveValue('Calle 20, puerta verde');
  await page.screenshot({ path: `/tmp/pagosya-fulfillment-${width}.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await method.selectOption('pickup');
  await expect(address).not.toBeVisible();
  await page.getByRole('button', { name: 'Continuar al pago de prueba' }).click();
  await expect(page.getByRole('heading', { name: 'Pago de prueba' })).toBeVisible();
  expect(errors).toEqual([]);
});
