ALTER TABLE "Store" ADD COLUMN "creditsEnabled" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "digitalGoodsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PaymentLink" ADD COLUMN "fulfillmentType" TEXT NOT NULL DEFAULT 'PHYSICAL';
CREATE TABLE "StoreCredit" (
"id" TEXT PRIMARY KEY, "storeId" TEXT NOT NULL REFERENCES "Store"("id") ON DELETE CASCADE ON UPDATE CASCADE,
"codeHash" TEXT NOT NULL UNIQUE, "reference" TEXT NOT NULL, "label" TEXT NOT NULL, "kind" TEXT NOT NULL DEFAULT 'GIFT_CARD',
"currency" TEXT NOT NULL, "issuedAmount" INTEGER NOT NULL CHECK ("issuedAmount" > 0), "balance" INTEGER NOT NULL CHECK ("balance" >= 0),
"active" BOOLEAN NOT NULL DEFAULT true, "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE ("storeId", "reference"));
CREATE TABLE "StoreCreditReservation" (
"paymentIntentId" TEXT PRIMARY KEY REFERENCES "PaymentIntent"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
"creditId" TEXT NOT NULL REFERENCES "StoreCredit"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
"amount" INTEGER NOT NULL CHECK ("amount" > 0), "refundedAmount" INTEGER NOT NULL DEFAULT 0,
"status" TEXT NOT NULL DEFAULT 'RESERVED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StoreCreditEntry" (
"id" TEXT PRIMARY KEY, "creditId" TEXT NOT NULL REFERENCES "StoreCredit"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
"reference" TEXT NOT NULL UNIQUE, "delta" INTEGER NOT NULL, "kind" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DigitalAsset" (
"id" TEXT PRIMARY KEY, "storeId" TEXT NOT NULL REFERENCES "Store"("id") ON DELETE CASCADE ON UPDATE CASCADE,
"productId" TEXT NOT NULL REFERENCES "PaymentLink"("id") ON DELETE CASCADE ON UPDATE CASCADE,
"storageKey" TEXT NOT NULL UNIQUE, "filename" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "byteSize" INTEGER NOT NULL,
"active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DigitalAsset_storeId_productId_active_idx" ON "DigitalAsset"("storeId", "productId", "active");
CREATE TABLE "StoreRedirect" (
"id" TEXT PRIMARY KEY, "storeId" TEXT NOT NULL REFERENCES "Store"("id") ON DELETE CASCADE ON UPDATE CASCADE,
"fromPath" TEXT NOT NULL, "toPath" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE ("storeId", "fromPath"));
