import { writeFile } from 'node:fs/promises';
const bolt = '<svg viewBox="0 0 48 56" aria-hidden="true"><path d="m28 3-23 30h17l-4 20L44 21H28z"/></svg>';
const cart = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h2l3 12h11l2-9H6M9 20h.01M18 20h.01"/></svg>';
const search = '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>';
const header = `<a class="skip" href="#contenido">Ir al contenido</a><div class="ticker"><span>${bolt} HISTORIAS DE UNA GALAXIA MUY, MUY LEJANA</span><span>ELIGE TU LADO. ENCUENTRA TU CÓMIC. ${bolt}</span></div><header class="masthead"><a class="wordmark" href="index.html" aria-label="Thunder and Pulp, inicio"><span class="logo-bolt">${bolt}</span><span>THUNDER <em>& PULP</em><small>CÓMICS · CULTURA GALÁCTICA</small></span></a><nav aria-label="Navegación principal"><a href="index.html#catalogo">LOS CÓMICS</a><a href="index.html#ediciones">LAS PORTADAS</a><a href="index.html#universo">EL UNIVERSO</a></nav><div class="header-tools"><a class="icon-control search-link" href="index.html#buscar" aria-label="Buscar cómics">${search}</a><button class="icon-control cart-trigger" type="button" data-cart-open aria-label="Abrir mi pedido">${cart}<span data-cart-count>0</span></button></div></header><div class="demo-strip">TIENDA CONCEPTUAL DE STAR WARS <span>CATÁLOGO Y PRECIOS DE EJEMPLO · SIN COBROS</span></div>`;
const footer = `<footer class="site-footer"><div><a href="index.html" class="footer-wordmark">THUNDER & PULP ${bolt}</a><p>Para quienes nunca dejaron de mirar las estrellas.</p></div><div><a href="index.html#catalogo">Explorar los cómics</a><a href="checkout.html">Revisar mi pedido</a><p>Demo independiente de pagosYa. Portadas: Marvel. Fondo creado con IA. <a href="credits.html">Créditos del arte</a>.<br>No es una tienda oficial. No se venden ni se envían productos.</p></div></footer><div data-pagosya-cart></div><p class="global-status" data-pagosya-status role="status" aria-live="polite"></p>`;
const contract = `<!-- THESIS: A tactile Star Wars comic shop built from the user's Thunder & Pulp screenshot. OWN-WORLD: warm paper, yellow, scarlet, heavy ink rules, Bangers comic display, Oswald labels, compact mono captions. STORY: inspect the artwork, choose a cover, add a sample comic, complete a no-charge checkout. FIRST VIEWPORT: compact masthead above a large photograph left and yellow title/cover choices/black purchase region right. FORM: screenshot-pinned product dossier; user explicitly requested this reference, no random selection. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md -->`;
function page(title, content, cls = '') { return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6cb19"><meta name="description" content="Una tienda conceptual de cómics Star Wars: explora las portadas y prueba un pedido sin cobros."><title>${title} · Thunder & Pulp</title><link rel="stylesheet" href="styles.css"><script src="config.js" defer></script><script src="commerce.js" defer></script><script src="site.js" defer></script></head><body class="${cls}">${contract}<div class="shop-shell">${header}${content}${footer}</div></body></html>`; }
const home = `<main id="contenido"><div class="breadcrumb"><a href="index.html">INICIO</a><span>/</span><a href="#catalogo">STAR WARS</a><span>/</span><strong>EL ARCHIVO GALÁCTICO</strong></div>
<section class="feature" aria-labelledby="feature-title"><div class="feature-media"><figure class="feature-photo"><img data-feature-image src="assets/hero.jpg" width="1200" height="900" alt="Portada de Star Wars (2025) número 1, ilustrada por Phil Noto" fetchpriority="high"><figcaption><span>UNA NUEVA AVENTURA EMPIEZA AQUÍ</span><span data-cover-count>1 / 3</span></figcaption></figure><div class="photo-strip"><span>MÁS DE ESTA GALAXIA ${bolt}</span><div class="photo-thumbs"><button type="button" data-cover="jedi" aria-label="Elegir portada Star Wars" aria-pressed="true"><img src="assets/hero.jpg" alt=""><span>EL JEDI</span></button><button type="button" data-cover="vader" aria-label="Elegir portada Darth Vader" aria-pressed="false"><img src="assets/vader.jpg" alt=""><span>EL LADO OSCURO</span></button><button type="button" data-cover="mando" aria-label="Elegir portada The Mandalorian" aria-pressed="false"><img src="assets/mando.jpg" alt=""><span>EL CAZARRECOMPENSAS</span></button></div></div></div>
<div class="feature-info"><div class="feature-title-panel"><div class="title-top"><span class="print-mark" aria-hidden="true">T&P</span></div><h1 id="feature-title">STAR WARS<br><span data-feature-title>Nº 01</span></h1><p data-feature-subtitle>UNA NUEVA ERA</p><div class="title-bottom"><span>AVENTURA · CIENCIA FICCIÓN</span><span>DEMO INTERACTIVO</span></div></div>
<section class="cover-options" id="ediciones" aria-label="Elegir cómic"><div class="panel-label"><h2>ELIGE TU HISTORIA</h2><span>3 PORTADAS</span></div><div class="cover-buttons"><button type="button" data-cover="jedi" aria-pressed="true"><span class="cover-swatch swatch-jedi"></span>Star Wars</button><button type="button" data-cover="vader" aria-pressed="false"><span class="cover-swatch swatch-vader"></span>Darth Vader</button><button type="button" data-cover="mando" aria-pressed="false"><span class="cover-swatch swatch-mando"></span>Mandalorian</button></div><p class="cover-description" data-feature-description>Luke, Leia y Han. El Imperio ha caído, pero la galaxia todavía tiene historias que contar.</p></section>
<div class="purchase-panel"><fieldset><legend>ARMA TU COLECCIÓN</legend><label class="purchase-option"><input type="radio" name="edition" value="single" checked><span><strong>ESTE EJEMPLAR</strong><small data-selected-name>Star Wars (2025) #1</small></span><b data-single-price>Bs 120</b></label><label class="purchase-option"><input type="radio" name="edition" value="collection"><span><strong>LA COLECCIÓN COMPLETA</strong><small>Las tres portadas de este demo</small></span><b>Bs 315</b></label></fieldset><button class="hero-buy" type="button" data-add="sw-jedi" data-feature-buy>AÑADIR AL PEDIDO <span data-feature-price>Bs 120</span>${bolt}</button><a class="detail-link" data-feature-link href="product.html?id=sw-jedi">VER EL DETALLE DEL CÓMIC <span aria-hidden="true">↗</span></a></div></div></section>
<section class="catalog-section" id="catalogo" aria-labelledby="catalog-title"><div class="catalog-heading"><div><h2 id="catalog-title">LA GALAXIA NO<br>TERMINA AQUÍ.</h2><p>El próximo capítulo de tu colección.</p></div><form class="catalog-search" id="buscar" role="search"><label for="comic-search">Encuentra tu historia</label><div><input type="search" id="comic-search" placeholder="Jedi, Vader, Mandalorian…" autocomplete="off"><button type="submit" aria-label="Buscar en el catálogo">${search}</button></div></form></div><div class="catalog-tools"><div data-pagosya-categories aria-label="Categorías"></div><span data-search-count>4 CÓMICS DE EJEMPLO</span></div><div class="comics-grid" data-pagosya-catalog></div><p class="search-empty" data-search-empty hidden>No encontramos ese cómic. Prueba con otro nombre o borra la búsqueda.</p><template data-pagosya-product-template><article class="comic-card"><a class="comic-art" data-product-link data-product-media><img data-product-field="image" alt=""></a><div class="comic-copy"><a data-product-link><h3 data-product-field="name"></h3></a><p data-product-field="description"></p><div class="comic-purchase"><strong data-product-field="price"></strong><button type="button" data-product-add>AÑADIR ${bolt}</button></div></div></article></template></section>
<section class="universe" id="universo"><div class="universe-art"><img src="assets/vader.jpg" alt="Portada de Darth Vader (2020) número 1" loading="lazy"></div><div class="universe-copy"><h2>ALGUNAS HISTORIAS<br>NO SE LEEN.<br><em>SE COLECCIONAN.</em></h2><p>El héroe. El villano. El que sigue su propio camino. Tres miradas a una galaxia que siempre tiene otra historia que contar.</p><a class="paper-button" href="#ediciones">ENCUENTRA TU LADO ${bolt}</a><small>Una exploración visual de la temática Club de papel.<br>Selección de cómics y precios de ejemplo. Demo sin cobros.</small></div></section></main>`;
await writeFile(new URL('index.html', import.meta.url), page('Star Wars · El archivo galáctico', home));
await writeFile(new URL('product.html', import.meta.url), page('El cómic', '<main id="contenido"><div class="breadcrumb"><a href="index.html#catalogo">VOLVER AL ARCHIVO</a><span>/</span>EL CÓMIC</div><section class="product-page" data-pagosya-product-page></section></main>', 'detail-document'));
await writeFile(new URL('checkout.html', import.meta.url), page('Tu pedido', '<main id="contenido"><section data-pagosya-checkout data-pagosya-checkout-page hidden></section></main>', 'checkout-document'));

await writeFile(new URL('credits.html', import.meta.url), page('Créditos del arte', `<main id="contenido" class="credits"><h1>EL ARTE DE ESTA GALAXIA</h1><p>Esta tienda es una demostración de diseño y compra sin cobros. Las portadas pertenecen a sus respectivos titulares y se presentan como referencia de los cómics.</p><ul><li><a href="https://www.marvel.com/comics/issue/119550/read">Star Wars (2025) #1</a> · Portada de Phil Noto · Marvel.</li><li><a href="https://www.marvel.com/comics/issue/80531/star-wars-darth-vader-2020-1">Darth Vader (2020) #1</a> · Portada de In-Hyuk Lee · Marvel.</li><li><a href="https://www.marvel.com/comics/issue/91476/star_wars_the_mandalorian_2022_1_variant">The Mandalorian (2022) #1, variante</a> · Portada de Leinil Francis Yu · Marvel.</li></ul><p>El fondo de la librería se creó con IA para este demo. La fotografía no representa un local real. Tipografías Bangers y Oswald, distribuidas bajo la SIL Open Font License.</p><a class="paper-button" href="index.html">VOLVER A LOS CÓMICS</a></main>`));
