const { chromium, expect } = require('../../apps/merchant-studio/node_modules/@playwright/test');
const fs = require('node:fs');
(async () => {
 const browser=await chromium.launch();
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 fs.mkdirSync(__dirname+'/.screenshots',{recursive:true});
 await page.goto('http://127.0.0.1:4316');await page.evaluate(()=>document.fonts.ready);
 await expect(page.locator('[data-pagosya-catalog] [data-product-id]')).toHaveCount(4);
 await expect(page.locator('img').filter({visible:true})).not.toHaveCount(0);
 await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));
 const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src));
 if(broken.length)throw Error('Broken images '+broken);
 await page.screenshot({path:__dirname+'/.screenshots/desktop.png',fullPage:true});
 await page.screenshot({path:__dirname+'/.screenshots/desktop-hero.png'});
 await page.locator('.cover-buttons [data-cover=vader]').click();
 await expect(page.locator('[data-feature-buy]')).toHaveAttribute('data-add','sw-vader');
 await expect(page.locator('[data-feature-image]')).toHaveAttribute('src','assets/vader.jpg');
 await page.locator('[value=collection]').check();
 await expect(page.locator('[data-feature-buy]')).toHaveAttribute('data-add','sw-collection');
 await page.locator('[data-feature-buy]').click();
 await page.locator('[data-cart-open]').first().click();
 await expect(page.locator('dialog[open] .order-total')).toContainText('315');
 await page.locator('dialog[open] [data-cart-close]').first().click();
 await page.locator('#comic-search').fill('Vader');
 await expect(page.locator('[data-pagosya-catalog] [data-product-id]:visible')).toHaveCount(2);
 await page.locator('#comic-search').fill('xyz-not-found');await expect(page.locator('[data-search-empty]')).toBeVisible();
 await page.locator('#comic-search').fill('');
 await page.locator('[data-product-id=sw-mando] [data-product-link]').first().click();
 await expect(page).toHaveURL(/product.html\?id=sw-mando/);
 await expect(page.locator('h1')).toContainText('Mandalorian');
 await page.screenshot({path:__dirname+'/.screenshots/product.png',fullPage:true});
 await page.locator('.product-detail__buy').click();
 await page.reload();await expect(page.locator('[data-cart-count]')).toHaveText('2');
 await page.locator('[data-cart-open]').first().click();
 await expect(page.locator('dialog[open] .order-total')).toContainText('425');
 await page.locator('dialog[open] [data-checkout]').click();await expect(page).toHaveURL(/checkout.html/);
 await page.screenshot({path:__dirname+'/.screenshots/checkout.png',fullPage:true});
 await page.locator('[data-pay]').click();await expect(page.locator('[data-finish-demo]')).toBeVisible();
 await page.locator('[data-finish-demo]').click();
 await expect(page.locator('[data-pagosya-status]').first()).toContainText('Prueba completada');
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});await page.goto('http://127.0.0.1:4316');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow at '+width);
  await page.screenshot({path:__dirname+'/.screenshots/mobile-'+width+'.png',fullPage:true});
  await page.locator('.cover-buttons [data-cover=mando]').click();
  await page.locator('[data-feature-buy]').click();await page.locator('[data-cart-open]').first().click();
  await expect(page.locator('dialog[open]')).toBeVisible();await page.locator('dialog[open] [data-checkout]').click();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Checkout overflow at '+width);
  await page.screenshot({path:__dirname+'/.screenshots/checkout-'+width+'.png',fullPage:true});
  await page.locator('[data-pay]').click();await page.locator('[data-finish-demo]').click();
  await expect(page.locator('[data-pagosya-status]').first()).toContainText('Prueba completada');
 }
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: cover and collection selection, search and empty state, product navigation, persistent cart totals, desktop/mobile no-charge checkout, image loading, 390/320px overflow, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
