(function(){
  'use strict';
  var imageMap={salvia:'assets/image-d5b34d383f0c.jpg',coral:'assets/image-9c4db2099869.jpg',marfil:'assets/image-dbdc2c596f17.jpg'};
  function key(text){text=(text||'').trim().toLowerCase();return Object.keys(imageMap).find(function(k){return text.indexOf(k)>-1})||''}
  function changeImage(root,src,label){var img=root&&root.querySelector('.ritual-main-image');if(!img||!src)return;img.classList.add('is-changing');window.setTimeout(function(){img.src=src;img.alt=label==='Los tres colores'?'Botella Ritual SAVIA en colores Salvia, Coral y Marfil':'Botella Ritual SAVIA en color '+label;img.classList.remove('is-changing')},90);root.querySelectorAll('.gallery-thumb').forEach(function(b){var active=b.dataset.gallerySrc===src;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active))})}
  function decorate(){document.querySelectorAll('[data-product-option]').forEach(function(btn){var k=key(btn.textContent);if(k){btn.classList.add('is-color','color-'+k);btn.dataset.colorName=k.charAt(0).toUpperCase()+k.slice(1)}})}
  function stickyText(root){var bar=document.querySelector('.mobile-purchase');if(!bar||!root)return;var selected=[];root.querySelectorAll('[data-product-option][aria-pressed="true"]').forEach(function(b){selected.push(b.textContent.trim())});var variant=bar.querySelector('[data-sticky-variant]');var price=bar.querySelector('[data-sticky-price]');if(variant)variant.textContent=selected.length?selected.join(' · '):'Botella Ritual';var source=root.querySelector('.ritual-price');if(price&&source)price.textContent=source.textContent.trim()}
  document.addEventListener('click',function(e){
    var thumb=e.target.closest('.gallery-thumb');if(thumb){changeImage(thumb.closest('.ritual-product'),thumb.dataset.gallerySrc,thumb.dataset.galleryLabel);return}
    var option=e.target.closest('[data-product-option]');if(option){var k=key(option.textContent),root=option.closest('.ritual-product');if(k&&root)changeImage(root,imageMap[k],k.charAt(0).toUpperCase()+k.slice(1));window.setTimeout(function(){decorate();stickyText(root)},30)}
    var q=e.target.closest('[data-qty-plus],[data-qty-minus]');if(q){var product=q.closest('.ritual-product'),out=product.querySelector('[data-qty-output]'),n=parseInt(out.value||out.textContent,10)||1;n+=q.hasAttribute('data-qty-plus')?1:-1;n=Math.max(1,Math.min(20,n));out.value=n;out.textContent=n}
    var add=e.target.closest('[data-product-add]');if(add&&!add.dataset.repeating){var product=add.closest('.ritual-product'),out=product&&product.querySelector('[data-qty-output]'),n=out?(parseInt(out.value||out.textContent,10)||1):1;add.classList.add('is-added');var old=add.textContent;add.textContent='Añadida';window.setTimeout(function(){add.classList.remove('is-added');add.textContent=old},900);if(n>1){add.dataset.repeating='true';for(var i=1;i<n;i++){(function(delay){window.setTimeout(function(){add.click()},delay)})(i*190)}window.setTimeout(function(){delete add.dataset.repeating},n*190+40)}}
    var sticky=e.target.closest('[data-sticky-add]');if(sticky){var original=document.querySelector('.ritual-product [data-product-add]');if(original)original.click()}
  });
  function setup(){decorate();var root=document.querySelector('.ritual-product');if(!root)return;stickyText(root);var add=root.querySelector('[data-product-add]'),bar=document.querySelector('.mobile-purchase');if(add&&bar&&'IntersectionObserver' in window){new IntersectionObserver(function(entries){bar.classList.toggle('is-visible',!entries[0].isIntersecting)},{threshold:.05}).observe(add)}}
  document.addEventListener('pagosya:ready',function(){window.setTimeout(setup,40)});
  if(document.readyState!=='loading')window.setTimeout(setup,80);else document.addEventListener('DOMContentLoaded',function(){window.setTimeout(setup,80)});
})();