import { API_BASE_URL, MerchantStudioApi } from './api';
import { escapeHtml as escape } from './studio-ui';
import { preserveDialogForms } from './dialog-form-state';
import './brand-profile.css';

export async function openCommercePlatform(api: MerchantStudioApi, storeId: string, section: 'credits' | 'digital' | 'redirects' | 'all' = 'all') {
  const title = { credits: 'Tarjetas de regalo y saldos', digital: 'Archivos digitales', redirects: 'Artículos y redirecciones', all: 'Saldos y archivos digitales' }[section];
  const dialog = document.createElement('dialog'); dialog.className = 'brand-dialog'; dialog.setAttribute('aria-label', title);
  let state: any; let busy = false; let message = ''; let issued: any = null; let issueReference = crypto.randomUUID(); let refundReference = crypto.randomUUID();
  document.body.append(dialog); dialog.innerHTML = '<p role="status">Cargando saldos y archivos…</p>'; dialog.showModal();
  dialog.addEventListener('close', () => dialog.remove()); dialog.addEventListener('cancel', e => { if (busy) e.preventDefault(); });
  try { state = await api.commercePlatform(storeId); render(); } catch (error) { dialog.textContent = error instanceof Error ? error.message : 'No se pudo cargar.'; const close = document.createElement('button'); close.textContent = 'Cerrar'; close.onclick = () => dialog.close(); dialog.append(close); }
  async function run(task: () => Promise<void>) {
    if (busy) return; const restore = preserveDialogForms(dialog); let failed = false; busy = true; message = '';
    dialog.querySelectorAll<HTMLInputElement>('input,select,button').forEach(el => el.disabled = true);
    try { await task(); state = await api.commercePlatform(storeId); } catch (e) { failed = true; message = e instanceof Error ? e.message : 'No se pudo guardar. Reintenta.'; }
    finally { busy = false; render(); if (failed) restore(); }
  }
  function money(amount: number, currency: string) { return `${(amount / 100).toFixed(2)} ${currency}`; }
  function render() {
    dialog.innerHTML = `<header><h2>${title}</h2><button class="button" data-close>Cerrar</button></header>
      <section class="brand-import" ${section !== 'all' && section !== 'credits' ? 'hidden' : ''}><h3>Tarjetas de regalo y saldo</h3><p>Emite un código para usar en esta tienda. Quien tenga el código puede gastar su saldo. Esta acción no cobra dinero al destinatario.</p>
      ${issued ? `<div role="status"><strong>Código emitido</strong><p><code style="overflow-wrap:anywhere">${escape(issued.code)}</code></p><p>${money(issued.balance, issued.currency)}. Guarda el código antes de cerrar.</p><button class="button" data-copy>Copiar código</button></div>` : ''}
      <form data-issue><div class="brand-fields"><label>Referencia o destinatario<input name="label" required maxlength="120"></label><label>Tipo<select name="kind"><option value="GIFT_CARD">Tarjeta de regalo</option><option value="STORE_CREDIT">Saldo de tienda</option></select></label><label>Importe<input name="amount" type="number" min="0.01" max="1000000" step="0.01" required></label><label>Moneda<select name="currency"><option>BOB</option><option>USD</option></select></label><label>Nombre del destinatario (opcional)<input name="recipientName" maxlength="120"></label><label>Correo del destinatario (opcional, tarjeta de regalo)<input name="recipientEmail" type="email" maxlength="254" placeholder="cliente@correo.com"></label><label>Vencimiento opcional<input name="expiresAt" type="datetime-local"></label></div><button class="button button--publish" type="submit">Emitir código de saldo</button></form>
      ${state.credits.map((credit: any) => `<article><strong>${escape(credit.label)}</strong><p>Disponible: ${money(credit.balance, credit.currency)} · ${credit.active ? 'Activo' : 'Pausado'}</p><button class="button" data-credit="${escape(credit.id)}">${credit.active ? 'Pausar código' : 'Activar código'}</button></article>`).join('') || '<p>Todavía no hay códigos emitidos.</p>'}
      <details><summary>Devolver saldo de un pedido</summary><p>Devuelve únicamente la parte pagada con saldo. El importe pagado por otro medio se reembolsa desde Pagos.</p><form data-refund><label>ID del pedido<input name="orderId" required maxlength="80"></label><label>Saldo a devolver<input name="amount" type="number" min="0.01" step="0.01" required></label><button class="button" type="submit">Devolver saldo</button></form></details></section>
      <section class="brand-import" ${section !== 'all' && section !== 'digital' ? 'hidden' : ''}><h3>Productos digitales</h3><p>Añade PDF, ZIP, EPUB, MP3 o MP4, hasta 50 MB. El producto se entregará por descarga después del pago. Los pedidos ya pagados conservan sus archivos aunque pauses nuevas ventas.</p>
      <form data-upload><label>Producto<select name="productId" required>${state.products.map((product: any) => `<option value="${escape(product.id)}">${escape(product.name)}</option>`).join('')}</select></label><label>Archivo privado<input name="file" type="file" accept=".pdf,.zip,.epub,.mp3,.mp4" required></label><button class="button button--publish" type="submit" ${!state.products.length ? 'disabled' : ''}>Añadir archivo digital</button></form>
      ${state.files.map((file: any) => `<article><strong>${escape(file.filename)}</strong><p>${escape(state.products.find((p: any) => p.id === file.productId)?.name || 'Producto archivado')} · ${(file.byteSize / 1000000).toFixed(2)} MB · ${file.active ? 'Disponible para nuevas compras' : 'Pausado'}</p><button class="button" data-file="${escape(file.id)}">${file.active ? 'Pausar archivo' : 'Activar archivo'}</button></article>`).join('') || '<p>No hay archivos digitales todavía.</p>'}</section>
      <section class="brand-import" ${section !== 'all' && section !== 'redirects' ? 'hidden' : ''}><h3>Artículos y redirecciones</h3><p><a href="${escape(API_BASE_URL)}/stores/public/${encodeURIComponent(state.storeSlug || '')}/pages" target="_blank" rel="noopener">Abrir artículos publicados</a> · <a href="${escape(API_BASE_URL)}/stores/public/${encodeURIComponent(state.storeSlug || '')}/sitemap.xml" target="_blank" rel="noopener">Sitemap</a> · <a href="${escape(API_BASE_URL)}/stores/public/${encodeURIComponent(state.storeSlug || '')}/rss.xml" target="_blank" rel="noopener">RSS</a></p><p>Redirige direcciones antiguas dentro de los artículos de esta tienda. Escribe /es/nombre-del-articulo. Estas reglas no modifican otros dominios.</p><form data-redirect><label>Ruta anterior<input name="fromPath" required maxlength="200" placeholder="/es/articulo-anterior"></label><label>Ruta nueva<input name="toPath" required maxlength="200" placeholder="/es/articulo-nuevo"></label><button class="button" type="submit">Guardar redirección</button></form>${(state.redirects || []).map((r: any) => `<article><p>${escape(r.fromPath)} → ${escape(r.toPath)}</p><button class="button" data-delete-redirect="${escape(r.id)}">Eliminar redirección</button></article>`).join('')}</section><p role="status">${escape(message)}</p>`;
    dialog.querySelector('[data-redirect]')?.addEventListener('submit', e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target as HTMLFormElement)); void run(async () => { await api.writeCommercePlatform(storeId, 'redirects', 'POST', data); message = 'Redirección guardada.'; }); });
    dialog.querySelectorAll<HTMLButtonElement>('[data-delete-redirect]').forEach(button => button.onclick = () => void run(async () => { await api.writeCommercePlatform(storeId, `redirects/${encodeURIComponent(button.dataset.deleteRedirect!)}`, 'DELETE', {}); }));
    dialog.querySelector('[data-close]')!.addEventListener('click', () => dialog.close());
    dialog.querySelector('[data-copy]')?.addEventListener('click', async e => { try { await navigator.clipboard.writeText(issued.code); (e.target as HTMLElement).textContent = 'Código copiado'; } catch { (e.target as HTMLElement).textContent = 'Selecciona el código para copiarlo'; } });
    dialog.querySelector('[data-issue]')!.addEventListener('submit', e => { e.preventDefault(); const data = new FormData(e.target as HTMLFormElement); void run(async () => { issued = await api.writeCommercePlatform(storeId, 'credits', 'POST', { reference: issueReference, label: data.get('label'), kind: data.get('kind'), currency: data.get('currency'), ...(data.get('recipientName') ? {recipientName: String(data.get('recipientName')).trim()} : {}), ...(data.get('recipientEmail') ? {recipientEmail: String(data.get('recipientEmail')).trim()} : {}), amount: Math.round(Number(data.get('amount')) * 100), ...(data.get('expiresAt') ? { expiresAt: new Date(String(data.get('expiresAt'))).toISOString() } : {}) }); issueReference = crypto.randomUUID(); }); });
    dialog.querySelector('[data-refund]')!.addEventListener('submit', e => { e.preventDefault(); const data = new FormData(e.target as HTMLFormElement); void run(async () => { await api.writeCommercePlatform(storeId, `orders/${encodeURIComponent(String(data.get('orderId')))}/credit-refund`, 'POST', { reference: refundReference, amount: Math.round(Number(data.get('amount')) * 100) }); refundReference = crypto.randomUUID(); message = 'Saldo devuelto al código original.'; }); });
    dialog.querySelector('[data-upload]')!.addEventListener('submit', e => { e.preventDefault(); const data = new FormData(e.target as HTMLFormElement); const file = data.get('file') as File; if (!file?.size) return; if (file.size > 50000000) { message = 'El archivo supera 50 MB.'; render(); return; } const productId = String(data.get('productId')); const upload = new FormData(); upload.set('file', file); void run(async () => { await api.uploadDigitalFile(storeId, productId, upload); message = 'Archivo añadido. El producto se entrega por descarga.'; }); });
    dialog.querySelectorAll<HTMLButtonElement>('[data-credit]').forEach(button => button.onclick = () => void run(async () => { const item = state.credits.find((c: any) => c.id === button.dataset.credit); await api.writeCommercePlatform(storeId, `credits/${encodeURIComponent(item.id)}`, 'PATCH', { active: !item.active }); }));
    dialog.querySelectorAll<HTMLButtonElement>('[data-file]').forEach(button => button.onclick = () => void run(async () => { const item = state.files.find((c: any) => c.id === button.dataset.file); await api.writeCommercePlatform(storeId, `files/${encodeURIComponent(item.id)}`, 'PATCH', { active: !item.active }); }));
  }
}
