import { preserveDialogForms } from './dialog-form-state';
import { MerchantStudioApi } from './api';
import { escapeHtml as escape } from './studio-ui';
import './brand-profile.css';

export async function openShippingSettings(api: MerchantStudioApi, storeId: string, onSaved?: () => void) {
  const dialog = document.createElement('dialog'); dialog.className = 'brand-dialog'; dialog.setAttribute('aria-label', 'Envíos y retiro');
  let state: any; let busy = false; let message = '';
  document.body.append(dialog); dialog.innerHTML = '<p role="status">Cargando envíos…</p>'; dialog.showModal();
  dialog.addEventListener('close', () => dialog.remove()); dialog.addEventListener('cancel', e => { if (busy) e.preventDefault(); });
  try { state = await api.shippingSettings(storeId); render(); } catch (e) { dialog.innerHTML = `<p>${escape(e instanceof Error ? e.message : 'No se pudieron cargar los envíos.')}</p><button>Cerrar</button>`; dialog.querySelector('button')!.onclick = () => dialog.close(); }
  async function run(task: () => Promise<void>) { if (busy) return; const restore = preserveDialogForms(dialog); let failed = false; busy = true; message = ''; dialog.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | HTMLButtonElement>('input,textarea,select,button').forEach(control => control.disabled = true); try { await task(); } catch (e) { failed = true; message = e instanceof Error ? e.message : 'No se pudo guardar.'; } finally { busy = false; render(); if (failed) restore(); } }
  function render() {
    dialog.innerHTML = `<header><h2>Envíos y retiro</h2><button class="button" id="shipping-close">Cerrar</button></header><p>Las tarifas se calculan con los productos del carrito y se incluyen en el pago. Los importes se muestran en la moneda elegida.</p>
      <form id="shipping-settings"><label><span><input type="checkbox" name="enabled" ${state.enabled ? 'checked' : ''} style="width:auto"> Activar tarifas de envío en checkout</span></label><label><span><input type="checkbox" name="pickupEnabled" ${state.pickupEnabled ? 'checked' : ''} style="width:auto"> Permitir retiro sin costo de envío</span></label><button class="button" type="submit">Guardar opciones</button></form>
      <section class="brand-import"><h3>Tarifas configuradas</h3>${state.rates.length ? state.rates.map((rate: any) => `<article><strong>${escape(rate.name)}</strong><p>${escape(rate.currency)} ${(rate.fee / 100).toFixed(2)}${rate.freeAbove !== null ? ` · Gratis desde ${(rate.freeAbove / 100).toFixed(2)}` : ''}${rate.countryCodes?.length ? ' · ' + escape(rate.countryCodes.join(', ')) : ''}${rate.postalPrefixes?.length ? ' · CP ' + escape(rate.postalPrefixes.join(', ')) : ''} · ${rate.isActive ? 'Activa' : 'Pausada'}</p><button class="button" data-toggle-rate="${escape(rate.id)}">${rate.isActive ? 'Pausar' : 'Activar'}</button></article>`).join('') : '<p>Aún no hay tarifas. Añade una antes de activar los envíos.</p>'}</section>
      <form id="shipping-rate" class="brand-import"><h3>Añadir tarifa</h3><div class="brand-fields"><label>Zona y servicio<input required maxlength="80" name="name" placeholder="La Paz · Entrega estándar"></label><label>Moneda<select name="currency"><option>BOB</option><option>USD</option></select></label><label>Costo de envío<input required type="number" name="fee" min="0" max="1000000" step="0.01"></label><label>Gratis desde<input type="number" name="freeAbove" min="0" max="1000000" step="0.01"></label><label>Pedido mínimo<input type="number" name="minimumOrder" min="0" max="1000000" step="0.01"></label><label>Pedido máximo<input type="number" name="maximumOrder" min="0" max="1000000" step="0.01"></label><label>Peso mínimo (gramos)<input type="number" name="minimumWeightGrams" min="0" max="100000000" step="1"></label><label>Peso máximo (gramos)<input type="number" name="maximumWeightGrams" min="0" max="100000000" step="1"></label><label>Países permitidos<input name="countryCodes" placeholder="BO, PE, CL" maxlength="749"></label><label>Prefijos postales permitidos<input name="postalPrefixes" placeholder="100, 200" maxlength="1299"></label></div><p>Países: códigos de dos letras separados por comas. Prefijos postales: letras y números, separados por comas. Vacío permite todos los destinos.</p><p>Deja los límites vacíos cuando no correspondan. Para usar tarifas por peso, cada producto necesita su peso de envío.</p><button class="button button--publish" type="submit">Añadir tarifa</button></form><section class="brand-import"><h3>Peso de los productos</h3><p>Incluye el empaque. Un peso desconocido impide aplicar tarifas limitadas por peso.</p>${(state.products || []).map((product: any) => `<form data-product-weight="${escape(product.id)}"><label>${escape(product.name)} · gramos<input name="weightGrams" type="number" min="0" max="100000000" step="1" value="${product.shippingWeightGrams ?? ''}"></label><button class="button" type="submit">Guardar peso</button></form>`).join('')}</section><p role="status">${escape(message)}</p>`;
    dialog.querySelectorAll<HTMLFormElement>('[data-product-weight]').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); const value = String(new FormData(form).get('weightGrams') || ''); void run(async () => { await api.saveShippingWeight(storeId, form.dataset.productWeight!, value ? Number(value) : null); state = await api.shippingSettings(storeId); message = 'Peso guardado.'; }); }));
    dialog.querySelector('#shipping-close')!.addEventListener('click', () => dialog.close());
    dialog.querySelector('#shipping-settings')!.addEventListener('submit', e => { e.preventDefault(); const form = new FormData(e.target as HTMLFormElement); void run(async () => { state = await api.saveShippingSettings(storeId, { enabled: form.has('enabled'), pickupEnabled: form.has('pickupEnabled') }); message = 'Opciones de entrega guardadas.'; onSaved?.(); }); });
    dialog.querySelector('#shipping-rate')!.addEventListener('submit', e => { e.preventDefault(); const form = new FormData(e.target as HTMLFormElement); const rate: Record<string, any> = { name: form.get('name'), currency: form.get('currency') }; for (const key of ['countryCodes', 'postalPrefixes']) rate[key] = String(form.get(key) || '').toUpperCase().split(',').map(value => value.replace(/[ -]/g, '')).filter(Boolean); for (const key of ['fee', 'freeAbove', 'minimumOrder', 'maximumOrder', 'minimumWeightGrams', 'maximumWeightGrams']) { const value = form.get(key); if (value !== '') rate[key] = Math.round(Number(value) * (key.includes('Weight') ? 1 : 100)); } void run(async () => { await api.createShippingRate(storeId, rate); state = await api.shippingSettings(storeId); message = 'Tarifa guardada.'; }); });
    dialog.querySelectorAll<HTMLButtonElement>('[data-toggle-rate]').forEach(button => button.onclick = () => void run(async () => { const rate = state.rates.find((r: any) => r.id === button.dataset.toggleRate); await api.toggleShippingRate(storeId, rate.id, !rate.isActive); state = await api.shippingSettings(storeId); }));
  }
}
