import { CHECKOUT_ORIGIN, type SourceVersion, type SourceState } from './api';
import { escapeHtml as escape } from './studio-ui';

export function renderSourcePublication(state: SourceState, version: SourceVersion | null, options: { locked: boolean; checking: boolean; failed: boolean; slug: string; expanded: boolean; detailsOpen: boolean }) {
  const publication = state.publication;
  const revision = publication?.revision;
  const experiment = publication?.experiment;
  const running = experiment?.status === 'RUNNING';
  const live = new URL(`/s/${encodeURIComponent(publication?.slug || options.slug)}`, CHECKOUT_ORIGIN);
  live.searchParams.set('source_owner', '1');
  const status = publication?.active === false ? 'Sin publicar' : running ? 'Prueba activa · comparando dos diseños' : revision ? 'Publicado' : 'Diseño sin publicar';
  const description = publication?.active === false ? 'Tu enlace público está oculto. El diseño sigue guardado y puedes volver a publicarlo con el interruptor de arriba.' : running ? 'Cada visitante ve uno de los dos diseños. Guardar cambios no modifica la prueba.' : revision ? version?.revision === revision ? 'Los clientes ven este diseño. Los próximos cambios quedan pendientes hasta que publiques.' : 'Los clientes siguen viendo el diseño publicado. Estos cambios todavía no modifican tu tienda.' : 'Tu enlace público sigue mostrando la tienda anterior. Publica este diseño cuando esté listo.';
  const blocked = options.locked || options.checking || options.failed || !version || running || publication?.active === false;
  const disable = (value: boolean) => value ? 'disabled' : '';
  const experimentResults = experiment ? `<div class="source-experiment-results"><p>${running ? 'En curso' : experiment.status === 'COMPLETED' ? `Finalizada · versión ${escape(experiment.winner || '')} aplicada` : 'Detenida · se conservó la versión A'} · desde ${escape(new Date(experiment.startedAt).toLocaleDateString('es-BO'))}</p><div class="source-results-scroll"><table><caption>Compras confirmadas · pagos reales, descontando reembolsos</caption><thead><tr><th>Versión</th><th>Visitantes</th><th>Compradores</th><th>Conversión</th><th>Ventas netas</th></tr></thead><tbody>${experiment.variants.map(row => `<tr><th>${row.variant} · r${row.revision}</th><td>${row.visitors}</td><td>${row.buyers}</td><td>${(row.conversionRate * 100).toFixed(1)}%</td><td>${row.revenue.length ? row.revenue.map(r => escape(new Intl.NumberFormat('es-BO', { style: 'currency', currency: r.currency }).format(r.amount / 100))).join('<br>') : 'Sin ventas'}</td></tr>`).join('')}</tbody></table></div><p role="status">${escape(experiment.evidence.reason)}</p><div class="source-publication-actions"><button class="button" id="source-test-refresh" ${disable(options.locked)}>Actualizar resultados</button>${running ? `<button class="button button--publish" id="source-test-apply" ${disable(options.locked || !experiment.evidence.winner)}>Aplicar ganador${experiment.evidence.winner ? ' ' + escape(experiment.evidence.winner) : ''}</button><button class="text-button" id="source-test-stop" ${disable(options.locked)}>Detener y conservar A</button>` : ''}</div></div>` : '';
  return `<section class="source-publication" aria-label="Publicación y prueba de ventas"><strong title="${escape(description)}">${escape(status)}${revision && version?.revision !== revision && !running ? ' <span class="source-draft-label">· Cambios pendientes</span>' : ''}</strong><details class="source-publication-details source-disclosure" ${options.detailsOpen ? 'open' : ''}><summary>Publicación y pruebas</summary><div class="source-disclosure-panel"><p>${escape(description)}</p><label class="source-form-option"><input id="source-contact-form" type="checkbox" ${publication?.contactFormEnabled ? 'checked' : ''} ${options.locked || (version && version.revision !== state.revision) ? 'disabled' : ''}> Formulario de contacto</label><p>Opcional. Al activarlo, los clientes pueden enviarte consultas al panel. Cambiarlo también actualiza la tienda publicada.</p>${running ? '<p>Despublicar detiene esta prueba. Al volver a publicar, todos verán el diseño A.</p>' : ''}${publication?.payments === 'test' ? '<p>Los cobros están en modo de prueba. Activa los pagos reales desde Cumplimiento para registrar ventas en la comparación.</p>' : ''}<div class="source-publication-actions">${publication?.active !== false ? `<a class="button" href="${escape(live.href)}" target="_blank" rel="noopener noreferrer">Ver tienda pública</a>` : ''}</div>
    <details class="source-experiments" ${options.expanded ? 'open' : ''}><summary>Comparar dos diseños${running ? ' · prueba en curso' : ''}</summary><div class="source-experiments-body"><p>YAPI crea una alternativa. La revisas y después repartes las visitas 50/50. Productos, precios y pagos usan el mismo catálogo.</p>${!running ? `<div class="source-publication-actions"><button class="button" id="source-alternative" ${disable(options.locked || !version || !revision)}>Crear alternativa con YAPI</button><button class="button" id="source-test-start" ${disable(blocked || !revision || version?.revision === revision)}>Probar estos cambios contra el publicado</button></div><p>Crear una alternativa usa el modelo y límite de créditos seleccionados. Iniciar la prueba muestra estos cambios a la mitad de los visitantes.</p>` : ''}${experimentResults}<p>La comparación cuenta navegadores únicos y compras durante una ventana de atribución de 30 días. Requiere al menos 7 días y suficientes compras; las visitas del editor y los pagos de prueba no cuentan. El ganador se aplica solo cuando tú lo eliges.</p></div></details></div></details></section>`;
}
