"use client";

import { cn } from "@/lib/utils";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";

const bars = [{ label: "LUN", value: 40, color: "bg-red-400" }, { label: "MAR", value: 60, color: "bg-blue-400" }, { label: "MIÉ", value: 25, color: "bg-green-400" }, { label: "JUE", value: 80, color: "bg-yellow-400" }, { label: "VIE", value: 65, color: "bg-purple-400" }];
const slices = [{ label: "QR", value: 35, color: "#f87171" }, { label: "Tarjeta", value: 25, color: "#4ade80" }, { label: "Banco", value: 25, color: "#60a5fa" }, { label: "Otros", value: 15, color: "#fbbf24" }];
const health = [{ label: "VENTAS", value: 85, color: "#f87171" }, { label: "PAGOS", value: 95, color: "#4ade80" }, { label: "STOCK", value: 75, color: "#60a5fa" }, { label: "VISITAS", value: 65, color: "#fbbf24" }, { label: "META", value: 80, color: "#a78bfa" }];
const coords = (value: number, index: number) => { const angle = Math.PI / 180 * (72 * index - 90); const radius = value / 100 * 80; return { x: 100 + radius * Math.cos(angle), y: 100 + radius * Math.sin(angle) }; };
const panel = "relative flex h-full w-full flex-col border-[3px] border-black bg-white p-6 shadow-[8px_8px_0_#000]";

function BarChart() {
  const [hovered, setHovered] = useState<number | null>(null); const reduce = useReducedMotion();
  return <section className={panel}><h3 className="mb-6 border-b-[3px] border-black pb-2 text-xl font-black uppercase">Ventas semanales</h3><div className="flex min-h-[150px] flex-1 items-end justify-between gap-2 sm:gap-4">{bars.map((item, index) => <div key={item.label} className="group relative flex h-full flex-1 items-end"><motion.div initial={reduce ? false : { height: 0 }} animate={{ height: `${item.value}%` }} transition={reduce ? { duration: 0 } : { type: "spring", stiffness: 200, damping: 20, delay: index * .1 }} onHoverStart={() => setHovered(index)} onHoverEnd={() => setHovered(null)} className={cn("relative z-10 flex w-full origin-bottom cursor-pointer items-center justify-center overflow-hidden border-[3px] border-black", item.color)} whileHover={reduce ? undefined : { scaleY: 1.08, scaleX: 1.04 }}><span className="font-mono text-xs font-bold text-black/80">{item.label}</span></motion.div><AnimatePresence>{hovered === index && <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 8 }} className="absolute bottom-full left-1/2 z-30 -mb-2 -translate-x-1/2 border-[3px] border-black bg-black px-3 py-1 text-sm font-black whitespace-nowrap text-white">{item.value}%</motion.div>}</AnimatePresence></div>)}</div></section>;
}

function RadarChart() {
  const [hovered, setHovered] = useState<string | null>(null); const reduce = useReducedMotion(); const path = health.map((item, index) => { const point = coords(item.value, index); return `${index ? "L" : "M"} ${point.x} ${point.y}`; }).join(" ") + " Z";
  return <section className={cn(panel, "flex-row gap-6 bg-zinc-50")}><div className="relative flex min-h-[250px] flex-1 items-center justify-center"><svg viewBox="0 0 200 200" className="h-full w-full max-w-75 overflow-visible">{[100, 75, 50, 25].map((level) => <path key={level} d={health.map((_, index) => { const point = coords(level, index); return `${index ? "L" : "M"} ${point.x} ${point.y}`; }).join(" ") + " Z"} fill="none" stroke="rgba(0,0,0,.14)" strokeWidth="2" strokeDasharray="4 4" />)}<motion.path d={path} fill="rgba(167,139,250,.5)" stroke="black" strokeWidth="4" strokeLinejoin="round" initial={reduce ? false : { scale: 0, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} style={{ originX: "50%", originY: "50%" }} />{health.map((item, index) => { const point = coords(item.value, index); return <circle key={item.label} cx={point.x} cy={point.y} r={hovered === item.label ? 10 : 6} fill={hovered === item.label ? item.color : "white"} stroke="black" strokeWidth="3" onMouseEnter={() => setHovered(item.label)} onMouseLeave={() => setHovered(null)} />; })}</svg></div><div className="flex w-40 flex-col justify-center gap-2"><h3 className="mb-2 border-b-[3px] border-black pb-2 text-xl font-black uppercase">Pulso</h3>{health.map((item) => <button type="button" key={item.label} onMouseEnter={() => setHovered(item.label)} onMouseLeave={() => setHovered(null)} className="flex items-center justify-between border-2 border-transparent p-2 text-left hover:border-black"><span className="flex items-center gap-2 font-mono text-xs font-bold"><i className="h-3 w-3 border-2 border-black" style={{ backgroundColor: item.color }} />{item.label}</span><strong>{item.value}%</strong></button>)}</div></section>;
}

function Donut() {
  const [hovered, setHovered] = useState<string | null>(null); let current = 0;
  return <section className={cn(panel, "items-center justify-between overflow-hidden")}><h3 className="z-10 mb-8 w-full border-b-[3px] border-black pb-2 text-center text-2xl font-black tracking-tighter uppercase">Medios de pago</h3><div className="flex h-full w-full flex-col items-center justify-center"><div className="relative h-64 w-64 md:h-80 md:w-80"><svg viewBox="-1.2 -1.2 2.4 2.4" className="h-full w-full -rotate-90 overflow-visible">{slices.map((slice) => { const start = current; const end = current + slice.value / 100; current = end; const point = (percent: number) => [Math.cos(2 * Math.PI * percent), Math.sin(2 * Math.PI * percent)]; const [sx, sy] = point(start); const [ex, ey] = point(end); return <path key={slice.label} d={`M ${sx} ${sy} A 1 1 0 ${slice.value > 50 ? 1 : 0} 1 ${ex} ${ey} L 0 0`} fill={slice.color} stroke="black" strokeWidth=".04" opacity={hovered && hovered !== slice.label ? .3 : 1} onMouseEnter={() => setHovered(slice.label)} onMouseLeave={() => setHovered(null)} />; })}<circle cx="0" cy="0" r=".55" fill="white" stroke="black" strokeWidth=".04" /></svg><div className="pointer-events-none absolute inset-0 grid place-content-center text-center"><strong className="text-3xl">{hovered ? `${slices.find((slice) => slice.label === hovered)?.value}%` : "100%"}</strong><span className="text-[10px] font-bold tracking-widest uppercase">{hovered || "TOTAL"}</span></div></div><div className="mt-6 grid w-full grid-cols-2 gap-2">{slices.map((slice) => <button type="button" key={slice.label} onMouseEnter={() => setHovered(slice.label)} onMouseLeave={() => setHovered(null)} className="flex items-center gap-2 border-2 border-transparent p-2 font-bold hover:border-black"><i className="h-3 w-3 border-2 border-black" style={{ backgroundColor: slice.color }} />{slice.label}</button>)}</div></div></section>;
}

export default function BentoDashboard() { return <div className="flex min-h-screen w-full flex-col bg-zinc-100 p-4 font-sans md:p-12"><div className="relative z-10 mx-auto flex w-full max-w-7xl flex-1 flex-col"><header className="mb-6 md:mb-10"><h1 className="mb-2 text-4xl font-black tracking-tighter uppercase md:text-6xl">Finanzas</h1><p className="text-xs font-bold tracking-widest text-zinc-500 uppercase md:text-sm">Resumen real de tu negocio</p></header><div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><div className="flex flex-col gap-6"><div className="min-h-[400px]"><BarChart /></div><div className="min-h-[400px]"><RadarChart /></div></div><div className="flex min-h-[500px]"><Donut /></div></div></div></div>; }
