/** Shared defaults for the conversation agent and every source generation/revision. */
export const SOURCE_SHOPPING_FLOW = `Default shopping flow for EVERY generated store:
- Pedido / Mi pedido / cart navigation opens the runtime's right-side cart drawer via a button with data-cart-open and a data-cart-count span. It must not jump to a homepage section or go straight to payment. Keep a hidden data-pagosya-cart slot for the runtime on catalog/product pages; the runtime makes it visible inside the drawer. Do not author another cart implementation.
- The drawer occupies roughly 40–50% of a desktop viewport (about 480–600px, never past the midpoint on wide screens), anchored to the right with a dimmed backdrop; use the full available width on phones. Show actual items, quantities, remove/decrement controls, subtotal, empty state, close/continue-shopping action and one clear checkout action. Preserve the cart across pages. Use native dialog focus management, Escape dismissal and focus return.
- Every successful add gives immediate visible confirmation: updated count plus an added/check state or short status message near the action, with subtle 160–250ms transform/opacity feedback. Repeated adds must remain responsive. Respect motion=off, keyboard interaction and prefers-reduced-motion; always retain the non-motion confirmation. Do not open the cart automatically on every add.
- Checkout is a dedicated full-screen page, not a small centered modal or a narrow form floating in empty space. On desktop give the questions a generous main column and the order summary a secondary column; stack on mobile. Use the same brand, readable labels, 44px touch targets, validation, back navigation and retained answers.
- Ask how the customer wants to receive the order: delivery or pickup, limited to the store/branch's enabled options. Pickup shows the actual branch/address; delivery asks for address and useful references, then the real configured shipping options and fees. Digital-only orders skip physical delivery questions. Never invent delivery availability, free shipping, pickup addresses or fees.
- Let customers optionally use their current location ONLY after explicitly pressing a location button and accepting browser permission. Manual address entry must always work, including denied/unavailable location and sandbox previews. A map pin is an optional enhancement only with a working supported map integration; never draw a fake map or imply that coordinates replace a required street address. Retain entered delivery information when continuing or going back.
- After fulfillment, let the customer choose among the actual pagosYa payment methods in the full-screen platform payment form. Keep the existing server-created checkout session and isolated simulated Studio payment preview. Do not invent payment fields, providers or client-side payment submission. The drawer's checkout action opens this flow; the checkout review's payment action proceeds directly to the platform payment form without another order-review modal.
These defaults apply on first creation and remain in force for shopping-flow edits; an unrelated local edit must preserve the existing homepage and visual identity.`;
